#!/usr/bin/env bash
# Setups the development environment.

# Stop on errors
set -e

ROOT="$( cd "$( dirname "$(readlink -f "$0")" )/.." >/dev/null 2>&1 && pwd )"
cd "${ROOT}"

python=$(which python3)

# Load common functions
source ./scripts/_common

if [ ! -d "venv" ]; then
    log.info "Initializing the virtual environment..."
    # For error 'executable `python` not found' run
    # rm -Rf ~/.local/share/virtualenv
    ${python} -m venv ./venv
fi

source ./venv/bin/activate
python="${ROOT}/venv/bin/python3"

pip="${python} -m pip"
uv="${ROOT}/venv/bin/uv"
prek="${ROOT}/venv/bin/prek"

log.info "Updating PIP..."
${pip} install --upgrade pip

log.info "Installing uv..."
${pip} install --upgrade uv==0.11.8

log.info "Installing development dependencies..."
${uv} pip install --upgrade -r requirements-dev.txt

log.info "Installing git hooks..."
${prek} install

echo '"""Custom components module."""' >custom_components/__init__.py
