---
name: "Release"

on:
  push:
    tags:
      - "[v0-9]+.[0-9]+*"

jobs:
  release:
    name: "Publish new release"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v6"

      - working-directory: ./custom_components
        run: |
          echo "package=$(ls -F | grep \/$ | sed -n "s/\///g;1p")" >> $GITHUB_ENV
          echo "release_version=$(git describe --tags | sed s/v//)" >> $GITHUB_ENV
      - working-directory: ./custom_components
        run: |
          echo "basedir=$(pwd)/${{ env.package }}" >> $GITHUB_ENV

      - name: "Setup Git"
        if: env.release_version != '' && success()
        run: |
          git config --global user.name "release"
          git config --global user.email "release@GitHub"

      - name: "Zip component dir"
        if: env.release_version != '' && success()
        working-directory: ./custom_components/${{ env.package }}
        run: |
          zip ${{ env.package }}.zip -r ./

      - name: "Release"
        if: env.release_version != '' && success()
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.basedir }}/${{ env.package }}.zip

  release-notes:
    name: "Compose release notes"
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v6

      - working-directory: ./custom_components
        run: |
          echo "release_version=$(git describe --tags | sed s/v//)" >> $GITHUB_ENV

      - name: "Set up Python"
        if: env.release_version != '' && success()
        uses: actions/setup-python@v6
        with:
          python-version-file: 'pyproject.toml'

      - name: "Install uv"
        if: env.release_version != '' && success()
        uses: astral-sh/setup-uv@v8.1.0
        with:
          version: "0.11.8"
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml
            uv.lock

      - name: "Install requirements"
        if: env.release_version != '' && success()
        run: uv sync --locked --group dev

      - name: "Update release notes"
        if: env.release_version != '' && success()
        run: uv run ./scripts/gen_releasenotes --token ${{ secrets.GITHUB_TOKEN }} --repo ${{ github.repository }} --release ${{ env.release_version }}
